language: go
go:
  - "1.11"

git:
  depth: 10

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install node -y
  - go get -u -v github.com/gohugoio/hugo
  - npm install -g gulp
  - npm install -g travis-ci-cloudfront-invalidation

install:
  - npm install

script:
  - npm run build

before_deploy:
  - npm run buil

deploy:
- provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t cbc_website_dev .
  - docker tag cbc_website_dev $DOCKER_ORGANIZATION/cbc_website_dev
  - docker push $DOCKER_ORGANIZATION/cbc_website_dev
  on:
    branch: develop
- provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t cbc_website_prod .
  - docker tag cbc_website_prod $DOCKER_ORGANIZATION/cbc_website_prod
  - docker push $DOCKER_ORGANIZATION/cbc_website_prod
  on:
    branch: master

# after_deploy:
#   - if [[ $TRAVIS_BRANCH = "master" ]]; then travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_ID_PROD -i '/*' -b 'master' -p $TRAVIS_PULL_REQUEST; fi
