baseURL: http://localhost:1313
languageCode: "en-us"
title: "CBC Hugo Site"


params:
  embed:
    - url: "http://www.pnas.org/content/107/16/7503.long"

    - url: "https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1319-7"

    - url: "https://almob.biomedcentral.com/articles/10.1186/s13015-017-0116-x"

    - url: "https://www.biorxiv.org/content/early/2017/10/04/173203"

    - url: "https://www.nature.com/articles/s41586-018-0279-8"
