---
baseURL: https://cbc.brown.edu/
languageCode: en-us
title: Computational Biology Core
theme: cbc
canonifyURLs: true
googleAnalytics: UA-115983496-1
pygmentsCodefences: true

menu:
  main:
  - name: Support
    url: "/support/"
    weight: 2
  - name: Services
    url: "/services/"
    weight: 3
  - name: Resources
    url: "/resources/"
    weight: 4
  - name: About
    url: "/about/"
    weight: 1
  - name: Blog
    url: "https://medium.com/brown-compbiocore"
    weight: 5
params:
  brown_url: https://www.brown.edu
  top: Center for Computational Biology of Human Disease
  address: 3 Davol Sq, Providence RI
  email: cbc-help@brown.edu
  hero:
    title: Computational Biology Core
    text: The COBRE-CBHD Computational Biology Core (CBC) integrates across multiple
      research focused Centers supporting data-intensive research using high-throughput
      DNA/RNA sequencing datasets. The CBC is a service focused Core Facility.
    button:
    - title: support
      accent: true
    - title: services
      accent: true
    - title: resources
      accent: true
    - title: blog
      accent: true
    - title: about
      accent: true
  triple:
    title: "# Featured News and Events"
    text: News and events from the Computational Biology Core
    box:
    - title: RI Microbiome Symposium
      text: Please join us at the Rhode Island Microbiome Symposium at Avedisian Hall
        (College of Pharmacy) at the University of Rhode Island on Jan 16–17.
        The RI Microbiome Symposium seeks to bring together active and potential
        microbiome researchers from Rhode Island and the Northeast to network
        and present their research in the field of microbiomics. [Register here.](https://web.uri.edu/riinbre/microbiome-symposium-2020/) 
      src: images/microbiome_symposium.png
    - title: IPA is now available
      text: The CBC has subscribed to a site-wide license to the Ingenuity Pathway
        Analysis Software tool, accessible to all researchers with a Brown affiliation.
      src: images/ipa.jpg
    - title: CBC Tools
      text: CBC launches new site with open source software, workshops, tutorials,
        and documentation. You can visit the new site [here](https://compbiocore.github.io).
      src: images/cbc-tools-site.png
  embed:
  - url: http://www.pnas.org/content/107/16/7503.long
  - url: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1319-7
  - url: https://almob.biomedcentral.com/articles/10.1186/s13015-017-0116-x
  - url: https://www.biorxiv.org/content/early/2017/10/04/173203
  - url: https://www.nature.com/articles/s41586-018-0279-8
  - url: https://www.nature.com/articles/s41588-018-0295-5
  - url: https://www.nature.com/articles/s41592-018-0218-5
  - url: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1592-0
  - url: https://academic.oup.com/bioinformatics/article/34/22/3801/5089231?searchresult=1
  - url: http://science.sciencemag.org/content/362/6418/eaav0725
  slider:
    title: "# Genomics in the News"
  footer:
    firstcolumn:
    - Computational Biology Core
    - 3 Davol Sq., Providence RI 02903
    - "[cbc-help@brown.edu](mailto:cbc-help@brown.edu)"
    secondcolumn:
    - "**Acknowledgements**"
    - Research reported on this website is supported by an Institutional Development
      Award (IDeA) from the National Institute of General Medical Sciences of the
      National Institutes of Health under grant number P20GM109035.
# Taxonomies
taxonomies:
  tag: "tags"
  type: "types"
  category: "category"
