---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.yml
  label: General
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/support
  label: Support
  create: all
  match: "**/*"
- type: directory
  path: content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
upload_dir: static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
